#!/usr/bin/env node
/* ==========================================================================
   Capture screenshots of every project in js/projects.js
   --------------------------------------------------------------------------
   npm install            (once — installs Playwright)
   npx playwright install chromium   (once — downloads the browser)
   npm run shots          (or: node scripts/screenshot.mjs)

   Options:
     --only <slug>        capture just one project (slug = lower-case title,
                          spaces → dashes, e.g. "project-one")
     --max-height <px>    tallest capture in px (default 4800). Tall captures
                          scroll inside the browser frame on hover.
     --viewport           capture only the first screen (1440×900)

   Saves JPEGs to assets/work/ and writes js/screenshots.js, which the site
   reads automatically. Projects with an explicit `image` keep that image.
   ========================================================================== */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import vm from "node:vm";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const flag = (name) => args.includes(`--${name}`);
const opt = (name, fallback) => {
  const i = args.indexOf(`--${name}`);
  return i > -1 && args[i + 1] ? args[i + 1] : fallback;
};

const only = opt("only", null);
const maxHeight = parseInt(opt("max-height", "4800"), 10);
const viewportOnly = flag("viewport");

const slugify = (s) =>
  String(s).toLowerCase().normalize("NFKD").replace(/[^\w\s-]/g, "").trim().replace(/[\s_-]+/g, "-");

// Load the project list exactly as the browser would.
const sandbox = { window: {} };
vm.runInNewContext(await readFile(path.join(ROOT, "js/projects.js"), "utf8"), sandbox);
const projects = (sandbox.window.PROJECTS || []).filter((p) => p.url && (!only || slugify(p.title) === only));

// Keep previously captured screenshots when running with --only.
const existing = { window: {} };
try {
  vm.runInNewContext(await readFile(path.join(ROOT, "js/screenshots.js"), "utf8"), existing);
} catch {}
const map = { ...(existing.window.SCREENSHOTS || {}) };

let chromium;
try {
  ({ chromium } = await import("playwright"));
} catch {
  console.error("Playwright is not installed. Run `npm install` then `npx playwright install chromium`.");
  process.exit(1);
}

await mkdir(path.join(ROOT, "assets/work"), { recursive: true });
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });

for (const p of projects) {
  const slug = slugify(p.title);
  const file = `assets/work/${slug}.jpg`;
  const page = await context.newPage();
  process.stdout.write(`→ ${p.title} (${p.url}) … `);
  try {
    await page.goto(p.url, { waitUntil: "networkidle", timeout: 60000 }).catch(() => {});
    await page.waitForTimeout(2000);

    // Scroll through the page so lazy-loaded images and scroll animations fire.
    await page.evaluate(async (limit) => {
      const step = window.innerHeight * 0.8;
      const end = Math.min(document.documentElement.scrollHeight, limit);
      for (let y = 0; y < end; y += step) {
        window.scrollTo(0, y);
        await new Promise((r) => setTimeout(r, 250));
      }
      window.scrollTo(0, 0);
    }, maxHeight);
    await page.waitForTimeout(1200);

    const height = viewportOnly
      ? 900
      : Math.min(maxHeight, await page.evaluate(() => document.documentElement.scrollHeight));

    await page.screenshot({
      path: path.join(ROOT, file),
      type: "jpeg",
      quality: 82,
      fullPage: !viewportOnly,
      clip: { x: 0, y: 0, width: 1440, height },
    });
    map[slug] = file;
    console.log(`saved ${file} (${height}px tall)`);
  } catch (err) {
    console.log(`failed: ${err.message}`);
  } finally {
    await page.close();
  }
}

await browser.close();

const out = `/* Auto-generated by scripts/screenshot.mjs — maps project slugs to screenshots.
   Safe to leave empty; projects without a screenshot get a generated cover. */
window.SCREENSHOTS = ${JSON.stringify(map, null, 2)};
`;
await writeFile(path.join(ROOT, "js/screenshots.js"), out);
console.log(`\nUpdated js/screenshots.js with ${Object.keys(map).length} screenshot(s).`);
